CREATE TABLE Employees (
	id SERIAL NOT NULL PRIMARY KEY UNIQUE,
	lastName VARCHAR(30) NOT NULL,
	firstName VARCHAR(30) NOT NULL,
	dateOfBirth DATE NOT NULL,
	phoneNumber VARCHAR(15) NOT NULL UNIQUE,
	recruitmentDate DATE NOT NULL,
	emial VARCHAR(50) NOT NULL UNIQUE
);